name = "ThorinDistributions"
uuid = "939a8ac6-5ed4-439a-9e85-9cbf7c2ce175"
authors = ["Oskar Laverny"]
version = "0.1.0"

[compat]
julia = "1.5.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
